version: '3.7'

services:
  snackbar-mysql-db:
    container_name: snackbar-mysql-db
    restart: always
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=snackbar
    ports:
      - 3307:3306
    networks:
      - snackbar_network
    volumes:
      - db:/var/lib/mysql
      - ./src/main/resources/db.migration/init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  snackbar_network:
    driver: bridge
    name: snackbar_network
volumes:
  db: